#!/usr/bin/env python3
"""One-time copy of Outwatch's data into TV Talk's database, under the show
'Survivor'. Reads a SQLite copy of the old `outwatch` D1 database and prints
SQL to run against `tvtalk`:

    npx wrangler d1 export outwatch --remote --output="$S/outwatch-export.sql"
    sqlite3 "$S/outwatch.sqlite" < "$S/outwatch-export.sql"
    npx wrangler d1 execute tvtalk --remote --json --command "SELECT users.id AS user_id, \\
        user_emails.email AS email FROM users LEFT JOIN user_emails \\
        ON user_emails.user_id = users.id" > "$S/tvtalk-roster.json"
    npx wrangler d1 execute tvtalk --remote --json \\
        --command "SELECT COALESCE(MAX(id), 0) AS max_id FROM posts"
    python3 -I scripts/import-to-tvtalk.py --outwatch "$S/outwatch.sqlite" \\
        --tvtalk-roster "$S/tvtalk-roster.json" \\
        --post-id-offset <max_id + 10000> > "$S/import.sql"

The output carries real emails. Keep it out of the repo (write it to a scratch
directory). Outwatch post ids are shifted by --post-id-offset so they cannot
collide with TV Talk's own, and replies and reactions are shifted with them.
Pad the offset well past TV Talk's MAX(posts.id): TV Talk stays live while the
SQL is reviewed, and a note posted there in the meantime takes the next id.
Seasons are looked up by number inside the SQL rather than by id, because
seasons added in Outwatch after 51 do not exist in TV Talk until this runs.

Every imported row points at a roster column, and notes and reactions at a
login, so the script refuses to print anything unless every Outwatch column
and login exists in TV Talk's roster on the same column. D1 enforces those
foreign keys, and a mismatch would otherwise fail the import part-way.

Stdlib only. It reads only the file it is given and never touches the network
or wrangler.
"""

import argparse
import json
import sqlite3
import sys

SHOW = "(SELECT id FROM shows WHERE name = 'Survivor')"


def q(value):
    if value is None:
        return "NULL"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def season(number):
    return f"(SELECT id FROM seasons WHERE show_id = {SHOW} AND number = {int(number)})"


def roster_problems(outwatch, tvtalk_rows):
    """Why TV Talk's roster can't take Outwatch's rows, or [] if it can.

    `tvtalk_rows` is TV Talk's users LEFT JOIN user_emails as dicts with
    `user_id` and `email`. Problems name columns, never addresses, so the
    output is safe to paste anywhere.
    """
    tv_columns = {row["user_id"] for row in tvtalk_rows}
    tv_logins = {
        (row["email"].lower(), row["user_id"]) for row in tvtalk_rows if row["email"] is not None
    }
    problems = []
    for (user_id,) in outwatch.execute("SELECT id FROM users ORDER BY id"):
        if user_id not in tv_columns:
            problems.append(f"Outwatch column {user_id} is not a TV Talk column")
    for email, user_id in outwatch.execute(
        "SELECT email, user_id FROM user_emails ORDER BY user_id, email"
    ):
        if (email.lower(), user_id) not in tv_logins:
            problems.append(
                f"a login on Outwatch column {user_id} is missing from TV Talk or on another column"
            )
    return problems


def load_wrangler_rows(path):
    with open(path) as f:
        data = json.load(f)
    # `wrangler d1 execute --json` prints one result object per statement.
    return data[0]["results"] if isinstance(data, list) else data["results"]


def generate(outwatch, post_id_offset):
    def rows(sql):
        return outwatch.execute(sql).fetchall()

    out = ["-- Generated by scripts/import-to-tvtalk.py. Contains real emails: do not commit."]

    for number, subtitle, url, episode_count in rows(
        "SELECT id, subtitle, wikipedia_url, episode_count FROM seasons ORDER BY id"
    ):
        out.append(
            "INSERT INTO seasons (show_id, number, subtitle, url, episode_count, created_at) "
            f"SELECT id, {q(number)}, {q(subtitle)}, {q(url)}, {q(episode_count)}, "
            "strftime('%Y-%m-%dT%H:%M:%fZ', 'now') FROM shows WHERE name = 'Survivor' "
            "ON CONFLICT (show_id, number) DO UPDATE SET subtitle = excluded.subtitle, "
            "url = excluded.url, episode_count = excluded.episode_count;"
        )

    for user_id, season_id, created_at in rows(
        "SELECT user_id, season_id, created_at FROM watched"
    ):
        out.append(
            "INSERT OR IGNORE INTO watched (user_id, season_id, created_at) "
            f"VALUES ({q(user_id)}, {season(season_id)}, {q(created_at)});"
        )

    for user_id, season_id in rows(
        "SELECT id, currently_watching_season_id FROM users "
        "WHERE currently_watching_season_id IS NOT NULL"
    ):
        out.append(
            "INSERT INTO currently_watching (user_id, show_id, season_id) "
            f"VALUES ({q(user_id)}, {SHOW}, {season(season_id)}) "
            "ON CONFLICT (user_id, show_id) DO UPDATE SET season_id = excluded.season_id;"
        )

    # Ascending id, so a reply's parent is always inserted before the reply.
    for (pid, season_id, episode, user_id, body, created_at, offset_secs,
         author_email, reply_to, edited_at) in rows(
        "SELECT id, season_id, episode, user_id, body, created_at, offset_secs, "
        "author_email, reply_to_post_id, edited_at FROM posts ORDER BY id"
    ):
        new_reply = None if reply_to is None else reply_to + post_id_offset
        out.append(
            "INSERT INTO posts (id, season_id, episode, user_id, body, created_at, "
            "offset_secs, author_email, reply_to_post_id, edited_at) VALUES ("
            f"{pid + post_id_offset}, {season(season_id)}, {q(episode)}, {q(user_id)}, "
            f"{q(body)}, {q(created_at)}, {q(offset_secs)}, {q(author_email)}, "
            f"{q(new_reply)}, {q(edited_at)});"
        )

    for post_id, email, emoji, created_at in rows(
        "SELECT post_id, email, emoji, created_at FROM reactions"
    ):
        out.append(
            "INSERT OR IGNORE INTO reactions (post_id, email, emoji, created_at) "
            f"VALUES ({post_id + post_id_offset}, {q(email)}, {q(emoji)}, {q(created_at)});"
        )

    for user_id, season_id, episode, created_at in rows(
        "SELECT user_id, season_id, episode, created_at FROM reveals"
    ):
        out.append(
            "INSERT OR IGNORE INTO reveals (user_id, season_id, episode, created_at) "
            f"VALUES ({q(user_id)}, {season(season_id)}, {q(episode)}, {q(created_at)});"
        )

    for user_id, season_id, episode, elapsed, running_since, last_activity in rows(
        "SELECT user_id, season_id, episode, elapsed_secs, running_since, last_activity_at "
        "FROM watch_sessions"
    ):
        out.append(
            "INSERT OR IGNORE INTO watch_sessions (user_id, season_id, episode, elapsed_secs, "
            f"running_since, last_activity_at) VALUES ({q(user_id)}, {season(season_id)}, "
            f"{q(episode)}, {q(elapsed)}, {q(running_since)}, {q(last_activity)});"
        )

    for user_id, season_id, episode, adjust, updated_at in rows(
        "SELECT user_id, season_id, episode, adjust_secs, updated_at FROM watch_offsets"
    ):
        out.append(
            "INSERT OR IGNORE INTO watch_offsets (user_id, season_id, episode, adjust_secs, "
            f"updated_at) VALUES ({q(user_id)}, {season(season_id)}, {q(episode)}, "
            f"{q(adjust)}, {q(updated_at)});"
        )

    for user_id, season_id, episode, status, reason, created_at in rows(
        "SELECT user_id, season_id, episode, status, reason, created_at FROM episode_statuses"
    ):
        out.append(
            "INSERT OR IGNORE INTO episode_statuses (user_id, season_id, episode, status, "
            f"reason, created_at) VALUES ({q(user_id)}, {season(season_id)}, {q(episode)}, "
            f"{q(status)}, {q(reason)}, {q(created_at)});"
        )

    # The later of the two marks, so neither app's bell lights up again for
    # notes its reader had already seen.
    for email, seen in rows(
        "SELECT email, feed_seen_at FROM user_emails WHERE feed_seen_at IS NOT NULL"
    ):
        out.append(
            f"UPDATE user_emails SET feed_seen_at = {q(seen)} WHERE email = {q(email)} "
            f"AND (feed_seen_at IS NULL OR feed_seen_at < {q(seen)});"
        )

    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--outwatch", required=True, help="SQLite copy of the outwatch database.")
    parser.add_argument(
        "--tvtalk-roster",
        required=True,
        help="`wrangler d1 execute tvtalk --json` output of users LEFT JOIN user_emails.",
    )
    parser.add_argument(
        "--post-id-offset",
        type=int,
        required=True,
        help="Padded past TV Talk's MAX(posts.id); Outwatch post ids are shifted by this.",
    )
    args = parser.parse_args()
    conn = sqlite3.connect(f"file:{args.outwatch}?mode=ro", uri=True)
    problems = roster_problems(conn, load_wrangler_rows(args.tvtalk_roster))
    if problems:
        sys.exit("Rosters differ; fix TV Talk's roster first:\n  " + "\n  ".join(problems))
    sys.stdout.write(generate(conn, args.post_id_offset))


if __name__ == "__main__":
    main()
