#!/usr/bin/env python3
"""One-time copy of Outwatch's data into TV Talk's database, under the show
'Survivor'. Reads a SQLite copy of the old `outwatch` D1 database and prints
SQL to run against `tvtalk`:

    npx wrangler d1 export outwatch --remote --output="$S/outwatch-export.sql"
    sqlite3 "$S/outwatch.sqlite" < "$S/outwatch-export.sql"
    npx wrangler d1 execute tvtalk --remote --json \\
        --command "SELECT COALESCE(MAX(id), 0) AS max_id FROM posts"
    python3 -I scripts/import-to-tvtalk.py --outwatch "$S/outwatch.sqlite" \\
        --post-id-offset <max_id> > "$S/import.sql"

The output carries real emails. Keep it out of the repo (write it to a scratch
directory). Outwatch post ids are shifted by --post-id-offset so they cannot
collide with TV Talk's own, and replies and reactions are shifted with them.
Seasons are looked up by number inside the SQL rather than by id, because
seasons added in Outwatch after 51 do not exist in TV Talk until this runs.

Stdlib only. It reads only the file it is given and never touches the network
or wrangler.
"""

import argparse
import sqlite3
import sys

SHOW = "(SELECT id FROM shows WHERE name = 'Survivor')"


def q(value):
    if value is None:
        return "NULL"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def season(number):
    return f"(SELECT id FROM seasons WHERE show_id = {SHOW} AND number = {int(number)})"


def generate(outwatch, post_id_offset):
    def rows(sql):
        return outwatch.execute(sql).fetchall()

    out = ["-- Generated by scripts/import-to-tvtalk.py. Contains real emails: do not commit."]

    for number, subtitle, url, episode_count in rows(
        "SELECT id, subtitle, wikipedia_url, episode_count FROM seasons ORDER BY id"
    ):
        out.append(
            "INSERT INTO seasons (show_id, number, subtitle, url, episode_count, created_at) "
            f"SELECT id, {q(number)}, {q(subtitle)}, {q(url)}, {q(episode_count)}, "
            "strftime('%Y-%m-%dT%H:%M:%fZ', 'now') FROM shows WHERE name = 'Survivor' "
            "ON CONFLICT (show_id, number) DO UPDATE SET subtitle = excluded.subtitle, "
            "url = excluded.url, episode_count = excluded.episode_count;"
        )

    for user_id, season_id, created_at in rows(
        "SELECT user_id, season_id, created_at FROM watched"
    ):
        out.append(
            "INSERT OR IGNORE INTO watched (user_id, season_id, created_at) "
            f"VALUES ({q(user_id)}, {season(season_id)}, {q(created_at)});"
        )

    for user_id, season_id in rows(
        "SELECT id, currently_watching_season_id FROM users "
        "WHERE currently_watching_season_id IS NOT NULL"
    ):
        out.append(
            "INSERT INTO currently_watching (user_id, show_id, season_id) "
            f"VALUES ({q(user_id)}, {SHOW}, {season(season_id)}) "
            "ON CONFLICT (user_id, show_id) DO UPDATE SET season_id = excluded.season_id;"
        )

    # Ascending id, so a reply's parent is always inserted before the reply.
    for (pid, season_id, episode, user_id, body, created_at, offset_secs,
         author_email, reply_to, edited_at) in rows(
        "SELECT id, season_id, episode, user_id, body, created_at, offset_secs, "
        "author_email, reply_to_post_id, edited_at FROM posts ORDER BY id"
    ):
        new_reply = None if reply_to is None else reply_to + post_id_offset
        out.append(
            "INSERT INTO posts (id, season_id, episode, user_id, body, created_at, "
            "offset_secs, author_email, reply_to_post_id, edited_at) VALUES ("
            f"{pid + post_id_offset}, {season(season_id)}, {q(episode)}, {q(user_id)}, "
            f"{q(body)}, {q(created_at)}, {q(offset_secs)}, {q(author_email)}, "
            f"{q(new_reply)}, {q(edited_at)});"
        )

    for post_id, email, emoji, created_at in rows(
        "SELECT post_id, email, emoji, created_at FROM reactions"
    ):
        out.append(
            "INSERT OR IGNORE INTO reactions (post_id, email, emoji, created_at) "
            f"VALUES ({post_id + post_id_offset}, {q(email)}, {q(emoji)}, {q(created_at)});"
        )

    for user_id, season_id, episode, created_at in rows(
        "SELECT user_id, season_id, episode, created_at FROM reveals"
    ):
        out.append(
            "INSERT OR IGNORE INTO reveals (user_id, season_id, episode, created_at) "
            f"VALUES ({q(user_id)}, {season(season_id)}, {q(episode)}, {q(created_at)});"
        )

    for user_id, season_id, episode, elapsed, running_since, last_activity in rows(
        "SELECT user_id, season_id, episode, elapsed_secs, running_since, last_activity_at "
        "FROM watch_sessions"
    ):
        out.append(
            "INSERT OR IGNORE INTO watch_sessions (user_id, season_id, episode, elapsed_secs, "
            f"running_since, last_activity_at) VALUES ({q(user_id)}, {season(season_id)}, "
            f"{q(episode)}, {q(elapsed)}, {q(running_since)}, {q(last_activity)});"
        )

    for user_id, season_id, episode, adjust, updated_at in rows(
        "SELECT user_id, season_id, episode, adjust_secs, updated_at FROM watch_offsets"
    ):
        out.append(
            "INSERT OR IGNORE INTO watch_offsets (user_id, season_id, episode, adjust_secs, "
            f"updated_at) VALUES ({q(user_id)}, {season(season_id)}, {q(episode)}, "
            f"{q(adjust)}, {q(updated_at)});"
        )

    for user_id, season_id, episode, status, reason, created_at in rows(
        "SELECT user_id, season_id, episode, status, reason, created_at FROM episode_statuses"
    ):
        out.append(
            "INSERT OR IGNORE INTO episode_statuses (user_id, season_id, episode, status, "
            f"reason, created_at) VALUES ({q(user_id)}, {season(season_id)}, {q(episode)}, "
            f"{q(status)}, {q(reason)}, {q(created_at)});"
        )

    # The later of the two marks, so neither app's bell lights up again for
    # notes its reader had already seen.
    for email, seen in rows(
        "SELECT email, feed_seen_at FROM user_emails WHERE feed_seen_at IS NOT NULL"
    ):
        out.append(
            f"UPDATE user_emails SET feed_seen_at = {q(seen)} WHERE email = {q(email)} "
            f"AND (feed_seen_at IS NULL OR feed_seen_at < {q(seen)});"
        )

    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--outwatch", required=True, help="SQLite copy of the outwatch database.")
    parser.add_argument(
        "--post-id-offset",
        type=int,
        required=True,
        help="TV Talk's current MAX(posts.id); Outwatch post ids are shifted by this.",
    )
    args = parser.parse_args()
    conn = sqlite3.connect(f"file:{args.outwatch}?mode=ro", uri=True)
    sys.stdout.write(generate(conn, args.post_id_offset))


if __name__ == "__main__":
    main()
